name: Hitting the cronjob endpoint every day at 06:00 UTC(11:30 IST) to notify all physicians

on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  build:
    name: Send a GET request via wget
    runs-on: ubuntu-latest
    steps:
      - name: wget request
        run: wget https://sekhmet.chiragghosh.dev/notify