name: Hitting the cronjob endpoint every day at 12:00 to notify all physicians

on:
  schedule:
    - cron: "15 7 * * *"
jobs:
  build:
    name: Send a GET request via wget
    runs-on: ubuntu-latest
    steps:
      - name: wget request
        run: wget https://sekhmet.chiragghosh.dev/notify